
-- MySQL Script generated by MySQL Workbench
-- march 19 17:11:11 2020
-- Model: New Model    Version: 3.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema KoffietentDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `KoffietentDB` ;

-- -----------------------------------------------------
-- Schema KoffietentDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KoffietentDB` DEFAULT CHARACTER SET utf8 ;
USE `KoffietentDB` ;

-- -----------------------------------------------------
-- Table `KoffietentDB`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`users` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NOT NULL,
  `name` TEXT NOT NULL,
  `middlename` TEXT NOT NULL,
  `lastname` TEXT NOT NULL,
  `profile_picture` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `phonenumber` TEXT NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP (0) NULL,
  `updated_at` TIMESTAMP (0) NULL,

  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoffietentDB`.`password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`Password_resets` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`Password_resets` (
  `email` varchar (60) NULL,
  `token` VARCHAR(60) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoffietentDB`.`Campingbaas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`Campingbaas` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`Campingbaas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` TEXT NOT NULL,
  `middlename` TEXT NOT NULL,
  `lastname` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `phonenumber` TEXT NOT NULL,
  `picture_small` TEXT NOT NULL,
  `picture_big` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `personal_color` VARCHAR(6) NULL,
  `personal_font` TEXT NULL,
  `personal_font_size` SMALLINT NULL,
  `is_oppercampingbaas` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoffietentDB`.`Activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`Activity` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`Activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `creator` INT NOT NULL,
  `description` TEXT NULL,
  `picture` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_creator_activity`
      FOREIGN KEY (`creator`)
          REFERENCES `KoffietentDB`.`Campingbaas` (`id`)
          ON DELETE CASCADE
          ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoffietentDB`.`Activity_Planned`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`Activity_Planned` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`Activity_Planned` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `existing_activity_id` INT NOT NULL,
  `start_datetime` DATETIME NULL,
  `end_datetime` DATETIME NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `display_picture` TEXT NULL,
  `creation_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Activities_Plannend_Activities1`
    FOREIGN KEY (`existing_activity_id`)
    REFERENCES `KoffietentDB`.`Activity` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoffietentDB`.`Campingbaas_Activitiy_Planned`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`Campingbaas_Activitiy_Planned` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`Campingbaas_Activitiy_Planned` (
  `campingbaas_id` INT NOT NULL,
  `activity_planned_id` INT NOT NULL,
  PRIMARY KEY (`campingbaas_id`, `activity_planned_id`),
  INDEX `fk_Campingbaas_has_Activities_Plannend_Campingbaas1_idx` (`campingbaas_id` ASC),
  INDEX `fk_Campingbaas_Activitiy_Planned_Activity_Planned1_idx` (`activity_planned_id` ASC),
  CONSTRAINT `fk_Campingbaas_has_Activities_Plannend_Campingbaas1`
    FOREIGN KEY (`campingbaas_id`)
    REFERENCES `KoffietentDB`.`Campingbaas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Campingbaas_Activitiy_Planned_Activity_Planned1`
    FOREIGN KEY (`activity_planned_id`)
    REFERENCES `KoffietentDB`.`Activity_Planned` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoffietentDB`.`Initiator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`Initiator` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`Initiator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `middlename` TEXT NOT NULL,
  `lastname` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `phonenumber` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoffietentDB`.`Initiative`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`Initiative` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`Initiative` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Initiator_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `datetime` DATETIME NOT NULL,
  `seen` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Initiative_Initiative_Person1_idx` (`Initiator_id` ASC),
  CONSTRAINT `fk_Initiative_Initiative_Person1`
    FOREIGN KEY (`Initiator_id`)
    REFERENCES `KoffietentDB`.`Initiator` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `KoffietentDB`.`Footer_Links`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`Footer_Link` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`Footer_Link` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(60) NOT NULL,
    `link` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `KoffietentDB`.`Sponsor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`Sponsor` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`Sponsor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `link` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoffietentDB`.`Vacancy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`Vacancy` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`Vacancy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `activity_planned_id` int NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `start_datetime` DATETIME NULL,
  `end_datetime` DATETIME NULL,
  `picture` TEXT NULL,
  `people_amount_required` int NOT NULL,
  `vacancy_filled` TINYINT(1) NOT NULL,
  `is_deleted` TINYINT(1) NOT NULL,
  `is_open` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_vacancy_activity_planned_idx` (`Activity_Planned_id` ASC),
  CONSTRAINT `fk_vacancy_activity_planned`
    FOREIGN KEY (`Activity_Planned_id`)
    REFERENCES `KoffietentDB`.`Activity_Planned` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoffietentDB`.`Application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`Application` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`Application` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vacancy_id` INT NULL,
  `firstname` TEXT NOT NULL,
  `middlename` TEXT NOT NULL,
  `lastname` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `phonenumber` TEXT NOT NULL,
  `application_letter` MEDIUMTEXT NOT NULL,
  `datetime` DATETIME NOT NULL,
  `seen` TINYINT(1) NOT NULL,
  `is_accepted` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Application_Vacancy1_idx` (`vacancy_id` ASC),
  CONSTRAINT `fk_Application_Vacancy1`
    FOREIGN KEY (`vacancy_id`)
    REFERENCES `KoffietentDB`.`Vacancy` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoffietentDB`.`Activity_Picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`Activity_Picture` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`Activity_Picture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `picture` TEXT NOT NULL,
  `Activity_Planned_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Activity_Picture_Activity_Planned1_idx` (`Activity_Planned_id` ASC),
  CONSTRAINT `fk_Activity_Picture_Activity_Planned1`
    FOREIGN KEY (`Activity_Planned_id`)
    REFERENCES `KoffietentDB`.`Activity_Planned` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoffietentDB`.`Donation_Target`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`Donation_Target` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`Donation_Target` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Activity_Planned_id` INT NULL,
  `donation_item` VARCHAR(45) NOT NULL,
  `donation_needed` DECIMAL(10,2) NOT NULL,
  `donation_received` DECIMAL(10,2) NOT NULL Default 0,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `datetime` DATETIME NOT NULL DEFAULT NOW(),
  `is_completed` TINYINT(1) NOT NULL DEFAULT false,
  PRIMARY KEY (`id`),
  INDEX `fk_Donation_Target_Activity_Planned1_idx` (`Activity_Planned_id` ASC),
  CONSTRAINT `fk_Donation_Target_Activity_Planned1`
    FOREIGN KEY (`Activity_Planned_id`)
    REFERENCES `KoffietentDB`.`Activity_Planned` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoffietentDB`.`Donation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`Donation` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`Donation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Donation_Target_id` INT NOT NULL,
  `donator_name` TEXT NOT NULL,
  `donator_middlename` TEXT NOT NULL,
  `donator_lastname` TEXT NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `donation_amount` DECIMAL(10,2) NOT NULL,
  `donator_email` TEXT NOT NULL,
  `donator_phonenumber` TEXT NOT NULL,
  `datetime` DATETIME NOT NULL DEFAULT NOW(),
  `is_received` TINYINT(1) NOT NULL DEFAULT false,
  `status` VARCHAR(40) null,
  PRIMARY KEY (`id`),
  INDEX `fk_Donation_Donation_Target1_idx` (`Donation_Target_id` ASC),
  CONSTRAINT `fk_Donation_Donation_Target1`
    FOREIGN KEY (`Donation_Target_id`)
    REFERENCES `KoffietentDB`.`Donation_Target` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoffietentDB`.`Singular_Items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoffietentDB`.`Singular_Items` ;

CREATE TABLE IF NOT EXISTS `KoffietentDB`.`Singular_Items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `homepage_logo` TEXT NULL,
  `homepage_title` TEXT NULL,
  `homepage_text` TEXT NULL,
  `homepage_picture` TEXT NULL,
  `coffee_title` varchar(45) NULL,
  `activity_title` varchar(45) NULL,
  `help_title` varchar(45) NULL,
  `donate_title` varchar(45) NULL,
  `coffee_picture` TEXT NULL,
  `activity_picture` TEXT NULL,
  `help_picture` TEXT NULL,
  `donate_picture` TEXT NULL,
  `coffee_text` TEXT NULL,
  `activity_text` TEXT NULL,
  `help_text` TEXT NULL,
  `donate_text` TEXT NULL,
  `coffee_button` varchar(45) NULL,
  `activity_button` varchar(45) NULL,
  `help_button` varchar(45) NULL,
  `donate_button` varchar(45) NULL,
  `opentime_monday` VARCHAR(45) NULL,
  `opentime_tuesday` VARCHAR(45) NULL,
  `opentime_wednesday` VARCHAR(45) NULL,
  `opentime_thursday` VARCHAR(45) NULL,
  `opentime_friday` VARCHAR(45) NULL,
  `opentime_saturday` VARCHAR(45) NULL,
  `opentime_sunday` VARCHAR(45) NULL,
  `instagram_api_key` VARCHAR(200) NULL,
  `facebook_link` VARCHAR(200) NULL,
  `instagram_link` VARCHAR(200) NULL,
  `twitter_link` VARCHAR(200) NULL,
  `email_link` VARCHAR(200) NULL,
  `adres_street` VARCHAR(50) NULL,
  `adres_place` VARCHAR(50) NULL,
  `location_link` VARCHAR(500) NULL,
  `contactpage_text` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

--
-- Table structure for table `messages`
--

CREATE TABLE `messages` (
    `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` TEXT NOT NULL,
    `email` TEXT NOT NULL,
    `message` TEXT NOT NULL,
    `unread` tinyint(1) NOT NULL DEFAULT 1,
    `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

